# Generated by Django 5.2.17 on 2026-10-02 09:54

import app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_model_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAnchor',
            fields=[
                ('token_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('turnstile_site_key', models.CharField(blank=True, default='', max_length=256)),
                ('turnstile_secret_key', app.fields.EncryptedTextField(blank=True, default='')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
