# Generated by Django 5.2.17 on 2026-10-02 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_sessionanchor_sitesettings'),
        ('chatgpt', '0011_account_health_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_active_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_sessions_per_account',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_idle_seconds',
            field=models.PositiveIntegerField(default=1800),
        ),
        migrations.CreateModel(
            name='SessionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(choices=[('active', '使用中'), ('waiting', '排队中')], default='waiting', max_length=16)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chatgpt_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_slots', to='chatgpt.chatgptaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('queued_at', 'id'),
                'indexes': [models.Index(fields=['state', 'queued_at'], name='slot_state_queue_idx')],
            },
        ),
    ]
