# Generated by Django 5.2.17 on 2026-10-02 11:38

import app.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_sitesettings_max_active_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='oidc_auto_link_by_username',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='oidc_auto_provision',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='oidc_client_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='oidc_client_secret',
            field=app.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='oidc_display_name',
            field=models.CharField(default='SSO', max_length=32),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='oidc_issuer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='oidc_link_admins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='oidc_redirect_uri',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='oidc_scopes',
            field=models.CharField(default='openid profile email', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='oidc_username_claim',
            field=models.CharField(default='preferred_username', max_length=64),
        ),
        migrations.CreateModel(
            name='OidcIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('issuer', 'subject'), name='unique_oidc_identity')],
            },
        ),
    ]
