# Generated by Django 5.2.17 on 2026-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_hide_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='turnstile_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
