# Generated by Django 5.2.17 on 2026-10-03 17:52

import app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_sitesettings_turnstile_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='OidcFlow',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', app.fields.EncryptedTextField(blank=True, default='')),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
